import Anthropic from '@anthropic-ai/sdk'
import fs from 'fs'
import path from 'path'

const client = new Anthropic()

let _skillPrompt: string | null = null

function getSkillPrompt(): string {
  if (!_skillPrompt) {
    const filePath = path.join(process.cwd(), 'prompts/humanizer.md')
    _skillPrompt = fs.readFileSync(filePath, 'utf-8')
  }
  return _skillPrompt
}

export async function humanizeReport(report: string): Promise<string> {
  let systemPrompt: string
  try {
    systemPrompt = getSkillPrompt()
  } catch {
    return report
  }

  const userPrompt = `Here is a marketing intelligence report generated by an AI analyst. Apply your full process to it: draft rewrite → AI-tell audit → final rewrite.

The report uses numbered sections like "1. **Section Title** —". Preserve that exact structure and numbering. Only rewrite the prose inside each section.

Return ONLY the final rewritten report — no commentary, no audit notes, no "changes made" section. Just the cleaned report text, ready to publish.

---

${report}`

  try {
    const message = await client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 4096,
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    })

    const content = message.content[0]
    if (content.type !== 'text') return report

    const result = content.text.trim()
    // Sanity check: if the result is drastically shorter, something went wrong
    if (result.length < report.length * 0.4) {
      console.warn('[humanize] Output suspiciously short, returning original')
      return report
    }

    console.log('[humanize] done, tokens:', message.usage)
    return result
  } catch (err) {
    console.error('[humanize] failed, returning original report:', err)
    return report
  }
}
